---
- name: Deploy Nginx in webservers
  gather_facts: false
  hosts: webservers
  vars:
    ansible_ssh_user: user
  become: true

  pre_tasks:
    - name: Wait for webservers to become reachable via Bastion
      ansible.builtin.wait_for_connection:
        delay: 0
        timeout: 300

  tasks:
    - name: Update cache and install Nginx using apt
      ansible.builtin.apt:
        name: nginx=1.24.0-2ubuntu7.17
        state: present
        update_cache: yes